### PR TITLE
Fix Compilation for kernel > 6.6.0 and refactor reading part

### PR DESCRIPTION
**Pull request by Rafae3lPires**
This patch brings serveral changes which are separated by commits:

- Remove unused code of xilinx
- Fix compilation for kernel > 6.6.0
- Fix buffer overflow
- Refactor of the reading part of CAN frames

### CODE REVIEW

**Comment by alexmohr** [comment]
Awesome! Thanks for the contribution. I'll test in it in the next couple of days and merge it afterwards :)

File: src/module/hlcan.c [hunk 1]
```diff
@@ -243,45 +243,38 @@ static void slc_bump(struct slcan *sl)
...
+
+	sl->rexpected =	1 + // HLCAN_PACKET_START
+		1 + // type byte
+		ext_id +
+		dlc +
+		1; // HLCAN_PACKET_END
+
+	if (dlc > HLCAN_MAX_CAN_PAYLOAD) {
+		sl->rstate = FRAME_ERROR;
+	}else if (sl->rcount >= sl->rexpected) {
```
Comment (alexmohr) [inline src/module/hlcan.c]: missing space before else

**Comment by alexmohr** [comment]
Build does not work on Arch linux running kernel 6.15.8 and gcc 12.

```
Building module
make -C /lib/modules/6.15.8-arch1-1/build/ M=/tmp/usb-can/src/module modules
make[1]: Entering directory '/usr/lib/modules/6.15.8-arch1-1/build'
make[2]: Entering directory '/tmp/usb-can/src/module'
  CC [M]  hlcan.o
hlcan.c: In function ‘hlcan_update_rstate’:
hlcan.c:258:30: error: ‘FRAME_ERROR’ undeclared (first use in this function); did you mean ‘TIME_ERROR’?
  258 |                 sl->rstate = FRAME_ERROR;
      |                              ^~~~~~~~~~~
      |                              TIME_ERROR
hlcan.c:258:30: note: each undeclared identifier is reported only once for each function it appears in
hlcan.c:272:19: error: ‘HLCAN_MAX_CAN_PAYLOAD’ undeclared (first use in this function)
  272 |         if (dlc > HLCAN_MAX_CAN_PAYLOAD) {
      |                   ^~~~~~~~~~~~~~~~~~~~~
hlcan.c: In function ‘slcan_unesc’:
hlcan.c:310:22: error: ‘FRAME_ERROR’ undeclared (first use in this function); did you mean ‘TIME_ERROR’?
  310 |                 case FRAME_ERROR:
      |                      ^~~~~~~~~~~
      |                      TIME_ERROR
In file included from /usr/lib/modules/6.15.8-arch1-1/build/include/linux/compiler_types.h:89,
                 from <command-line>:
/usr/lib/modules/6.15.8-arch1-1/build/include/linux/compiler_attributes.h:214:41: warning: attribute ‘fallthrough’ not preceding a case label or default label
  214 | # define fallthrough                    __attribute__((__fallthrough__))
      |                                         ^~~~~~~~~~~~~
hlcan.c:309:25: note: in expansion of macro ‘fallthrough’
  309 |                         fallthrough;
      |                         ^~~~~~~~~~~
make[4]: *** [/usr/lib/modules/6.15.8-arch1-1/build/scripts/Makefile.build:203: hlcan.o] Error 1
make[3]: *** [/usr/lib/modules/6.15.8-arch1-1/build/Makefile:2003: .] Error 2
make[2]: *** [/usr/lib/modules/6.15.8-arch1-1/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/tmp/usb-can/src/module'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.15.8-arch1-1/build'
make: *** [Makefile:11: all] Error 2
Building userpace tools
cc -O2 -Wall -Wno-parentheses -D_GNU_SOURCE   hlcand.c   -o hlcand
```

--- 

Same error on debian 12, running 6.1.0.

@Rafae3lPires Are you interested in fixing this yourself? If not let know :)
Which kernel did you test with?

**Comment by Rafae3lPires** [comment]
> Build does not work on Arch linux running kernel 6.15.8 and gcc 12.
> 
> ```
> Building module
> make -C /lib/modules/6.15.8-arch1-1/build/ M=/tmp/usb-can/src/module modules
> make[1]: Entering directory '/usr/lib/modules/6.15.8-arch1-1/build'
> make[2]: Entering directory '/tmp/usb-can/src/module'
>   CC [M]  hlcan.o
> hlcan.c: In function ‘hlcan_update_rstate’:
> hlcan.c:258:30: error: ‘FRAME_ERROR’ undeclared (first use in this function); did you mean ‘TIME_ERROR’?
>   258 |                 sl->rstate = FRAME_ERROR;
>       |                              ^~~~~~~~~~~
>       |                              TIME_ERROR
> hlcan.c:258:30: note: each undeclared identifier is reported only once for each function it appears in
> hlcan.c:272:19: error: ‘HLCAN_MAX_CAN_PAYLOAD’ undeclared (first use in this function)
>   272 |         if (dlc > HLCAN_MAX_CAN_PAYLOAD) {
>       |                   ^~~~~~~~~~~~~~~~~~~~~
> hlcan.c: In function ‘slcan_unesc’:
> hlcan.c:310:22: error: ‘FRAME_ERROR’ undeclared (first use in this function); did you mean ‘TIME_ERROR’?
>   310 |                 case FRAME_ERROR:
>       |                      ^~~~~~~~~~~
>       |                      TIME_ERROR
> In file included from /usr/lib/modules/6.15.8-arch1-1/build/include/linux/compiler_types.h:89,
>                  from <command-line>:
> /usr/lib/modules/6.15.8-arch1-1/build/include/linux/compiler_attributes.h:214:41: warning: attribute ‘fallthrough’ not preceding a case label or default label
>   214 | # define fallthrough                    __attribute__((__fallthrough__))
>       |                                         ^~~~~~~~~~~~~
> hlcan.c:309:25: note: in expansion of macro ‘fallthrough’
>   309 |                         fallthrough;
>       |                         ^~~~~~~~~~~
> make[4]: *** [/usr/lib/modules/6.15.8-arch1-1/build/scripts/Makefile.build:203: hlcan.o] Error 1
> make[3]: *** [/usr/lib/modules/6.15.8-arch1-1/build/Makefile:2003: .] Error 2
> make[2]: *** [/usr/lib/modules/6.15.8-arch1-1/build/Makefile:248: __sub-make] Error 2
> make[2]: Leaving directory '/tmp/usb-can/src/module'
> make[1]: *** [Makefile:248: __sub-make] Error 2
> make[1]: Leaving directory '/usr/lib/modules/6.15.8-arch1-1/build'
> make: *** [Makefile:11: all] Error 2
> Building userpace tools
> cc -O2 -Wall -Wno-parentheses -D_GNU_SOURCE   hlcand.c   -o hlcand
> ```
> 
> Same error on debian 12, running 6.1.0.
> 
> @Rafae3lPires Are you interested in fixing this yourself? If not let know :) Which kernel did you test with?

yes I forgot to commit the .h file! sorry...
I did compile with the: 6.8.0-51
I will submit the missing changes

**Review by Rafae3lPires — COMMENTED** [review]
Can you please try again?

File: src/module/hlcan.c (hunk 1 above)
Comment (Rafae3lPires) [reply src/module/hlcan.c]: done

**Comment by alexmohr** [comment]
Works on both systems I posted earlier. Thanks again for contributing here :)
