### ISSUE TITLE
Can't compile with new kernel 5.13.19-2

### ISSUE THREAD

**Issue by rrov1** [alexmohr/usb-can#29]
Hi,

I have upgraded my linux system and also got a new kernel. Now I'm not able to compile usb-can any more. I get the following error:
`~/usb-can# ./build.sh`
`Building module`
`make -C /lib/modules/5.13.19-2-pve/build/ M=/root/usb-can/src/module modules`
`make[1]: Entering directory '/usr/src/linux-headers-5.13.19-2-pve'`
`  CC [M]  /root/usb-can/src/module/hlcan.o`
`/root/usb-can/src/module/hlcan.c:764:3: error: ‘struct tty_ldisc_ops’ has no member named ‘magic’`
`  764 |  .magic  = TTY_LDISC_MAGIC,`
`         |   ^~~~~`
`/root/usb-can/src/module/hlcan.c:764:12: error: ‘TTY_LDISC_MAGIC’ undeclared here (not in a function); did you mean ‘TTY_LDISC_HALTED’?`
`  764 |  .magic  = TTY_LDISC_MAGIC,`
`      |            ^~~~~~~~~~~~~~~`
`      |            TTY_LDISC_HALTED`
`make[2]: *** [scripts/Makefile.build:281: /root/usb-can/src/module/hlcan.o] Error 1`
`make[1]: *** [Makefile:1879: /root/usb-can/src/module] Error 2`
`make[1]: Leaving directory '/usr/src/linux-headers-5.13.19-2-pve'`
`make: *** [Makefile:11: all] Error 2`

As far as I'm able to check there ara some recent changes in the linux kernel 5.13: https://lore.kernel.org/lkml/YIa3d%2FxiS%2FpbBudv@kroah.com/

Because I'm not a very good programmer, I will roll back to an older kernel. I hope there is someone who can fix this.

regards,

rrov

**Comment by alexmohr** [comment]
Thanks for providing the kernel changelog. I'll try to fix the issue in the next couple of days

**Comment by alexmohr** [comment]
Actually there where multiple changes between 5.13 and 5.16 and I'd rather just fix it for the latest version. Would kernel 5.16 work for you too?

**Comment by rrov1** [comment]
I use proxmox 7.1 and get currently 5.13 from their repos. For now I have a solution to use a 5.11 kernel and I can wait until 5.16 is available. So yes, you can fix it for the latest kernel and I will upgrade if possible for me.

Thank you very much.

**Comment by alexmohr** [comment]
As 5.16 is still a bit away you can use this branch for kernel 5.13. 
Please note that 5.14 introduces additional changes to the serial interface and requires more fixing. Same goes for 5.16. 
I've created separate issues for these.

I've tested on `5.13.10` so it should work on your kernel as well. 
Please close this issue when the bug is resolved.

**Comment by rrov1** [comment]
After a buisy week I was able to successfully compile the kernel-3.15 branch.
Thank you very much!
